### ISSUE TITLE
[TOPP::ComputeProfiles] failed: CLC failed

### ISSUE THREAD

**Issue by kx-guan** [Tastalian/surface-contacts-icra-2015#1]
Hi, Carson:
   From generate_motion.py, the following error messages appeared:

[TOPP] (a, b, c) computation: 5.65 s
IntegrateForward INT_BOTTOM, s=5.689403454912973e+00, sd=5.608232237136747e-01
CLC failed
[TOPP::ComputeProfiles] failed: CLC failed
Traceback (most recent call last):
  File "./generate_motion.py", line 366, in <module>
    retimed_traj = hrp.topp.retime_trajectory(original_traj, 0., 0.)
  File "....../dmotions/hrp4/topp/retimer.py", line 88, in retime_trajectory
    topp_traj = topp_inst.Reparameterize(sd_beg, sd_end)
  File "/usr/local/lib/python2.7/dist-packages/TOPP/QuadraticConstraints.py", line 50, in Reparameterize
    raise NoTrajectoryFound(return_code)
TOPP.Errors.NoTrajectoryFound: unspecified error

 Would you like to give me some advice?
 Thank you very much.

**Comment by stephane-caron** [comment]
Looks like a TOPP issue. Can you check that you are using commit ``5370e95f635ac9e50538bb748fd93cee4758fcc9`` from the [TOPP repository](https://github.com/quangounet/TOPP)?

At any rate, the HRP-4 motion generation code from this project is quite outdated. I would recommend you look at the code from more recent projects such as [capture-walking](https://github.com/stephane-caron/capture-walking), or the [stair climbing](https://github.com/stephane-caron/stair-climbing) experiments we did with @wine3603.
